---
apiVersion: v1
kind: Pod
metadata:
  name: pod-com-volume-emptydir
  namespace: devops
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: backup-volume
      mountPath: /backup
  volumes:
  - name: backup-volume
    emptyDir: {}
