---
apiVersion: v1
kind: Pod
metadata:
  name: pod-com-volume-hostpath
  namespace: devops
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: site
      mountPath: /usr/share/nginx/html
  volumes:
  - name: site
    hostPath:
      path: /opt/site
      type: DirectoryOrCreate
