---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
