---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmaps
              key: MYSQL_DATABASE   
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmaps
              key: MYSQL_USER   
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD   

        volumeMounts:
        - name: claim-mysql
          mountPath: /var/lib/mysql

        - name: mysql-db-config
          mountPath: /docker-entrypoint-initdb.d/

        - name: dump-usuarios
          mountPath: /dump/

      volumes:
        - name: claim-mysql
          persistentVolumeClaim:
            claimName: claim-mysql

        - name: mysql-db-config
          configMap:
            name: mysql-db-config

        - name: dump-usuarios
          configMap:
            name: dump-usuarios
