---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  DB_PASS: NGxpbnV4
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
data:
  MYSQL_PASSWORD: NGxpbnV4
  MYSQL_ROOT_PASSWORD: QWJjMTIzIQ==
