---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: 3-ingress-pod-client-from-webserver
  namespace: devops
spec:
  podSelector:
    matchLabels:
      curso: rancher
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: php
