---
apiVersion: v1
kind: Pod
metadata:
  name: pod-client
  namespace: developer
  labels:
    curso: rancher
spec:
  containers:
  - name: alpine
    image: alpine
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
