---
apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox
  namespace: default
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
