---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver-tls
  namespace: devops
spec:
  defaultBackend:
    service:
      name: webserver
      port:
        number: 80
  tls:
  - secretName: webserver-cert
